### PR TITLE
Reachability analyzer (primarily for iiwa)

### PR DESCRIPTION
**Pull request by gizatt**
First version of a reachability / workspace analyzer, including some visualization of the results from running it on the IIWA (in a representative plane). See README.md in new subfolder for some details & pretty results

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/128)

### CODE REVIEW

**Comment by manuelli** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ReachabilityAnalyzer/CMakeLists.txt, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhcFWKTX2VsHrm9L6_:-KvhcFWL0KXcCxr7XisW:b9ysi15) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/CMakeLists.txt#L8)):*
> ```CMake
> find_package(gflags REQUIRED)
> 
> set(EIGEN3_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include/eigen3)
> ```

Is this the right way to find Eigen headers? I think `find_package(Eigen)` is more appropriate. Probably just do it however `director` does it. Is this getting `drake` Eigen?

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhcbqXFRo_1fljLr9q:-KvhcbqXFRo_1fljLr9r:b-r03rw0) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L46)):*
> ```cpp
> 
>   // Iteration information to define the volume we'll search.
>   Vector3i steps(50, 1, 50);
> ```

ok for now, but consider moving this to a yaml param file. The hope is that this would be extensible to different robots.

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 73 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhctXVCaw70nTehIJT:-KvhctXVCaw70nTehIJU:b-4hxr5l) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L73)):*
> ```cpp
>   name_map.push_back("-y");
>   name_map.push_back("+z");
>   name_map.push_back("-z");
> ```

wouldn't it make more sense to have this in a `std::map` with keys `"+x",+y"` etc. and then store color and grasp direction together.

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhdXmJ0oTSbO2V5udO:-KvhdXmJ0oTSbO2V5udP:b-m2cmnz) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L165)):*
> ```cpp
>           inverseKin(model.get(), q0, qnom, constraint_array.size(),
>                      constraint_array.data(), ikoptions, &q_sol, &info,
>                      &infeasible_constraint);
> ```

can we break all of this into a function call rather than it being inside the for loop? Like you give it the position orientation info and it sets up and solves the problem. Then it fills in the data structure that records the results of the IK solve, what color to draw etc. This would be more modular, but if it's a lot of work I'm fine with this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/128)*

**Comment by manuelli** [comment]
Jenkins please test

**Comment by gizatt** [comment]
I'll address reviews and tidy this up tomorrow so it can be brought in. In particular, I'll see about documenting how to load this into director and visualize it... should be as simple as saving and loading the VTK geometry into a Director window with the arm visualized.

**Comment by gizatt** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/ReachabilityAnalyzer/CMakeLists.txt, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhcFWKTX2VsHrm9L6_:-KwaWcDFyScFAPOGcvh-:b-896fix) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/CMakeLists.txt#L8)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

Is this the right way to find Eigen headers? I think `find_package(Eigen)` is more appropriate. Probably just do it however `director` does it. Is this getting `drake` Eigen?
</blockquote></details>

Done.

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhcbqXFRo_1fljLr9q:-KwamOTmCmt01wXPpQ-B:b-896fix) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L46)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

ok for now, but consider moving this to a yaml param file. The hope is that this would be extensible to different robots.
</blockquote></details>

Done.

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 73 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhctXVCaw70nTehIJT:-KwasNA6Y08xQgFWN6ET:b-8o5hdk) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L73)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

wouldn't it make more sense to have this in a `std::map` with keys `"+x",+y"` etc. and then store color and grasp direction together.
</blockquote></details>

Good point, done

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhdXmJ0oTSbO2V5udO:-KwayMN5Hc9fTgdybcu0:b-1i698x) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L165)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

can we break all of this into a function call rather than it being inside the for loop? Like you give it the position orientation info and it sets up and solves the problem. Then it fills in the data structure that records the results of the IK solve, what color to draw etc. This would be more modular, but if it's a lot of work I'm fine with this. 
</blockquote></details>

Working on this one now, shouldn't be too bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/128)*

**Comment by gizatt** [comment]
This has gotten a bit bigger, in that I've introduced a `common_utils` package in `spartan/src/common_utils` with some headers containing a bunch of generally-useful static function definitions. It's header-only for convenience (no linking required to use them, which also means their install logic is very simple, and always just installs them, with linking being the responsibility of the user); that can be fixed up if people want, probably on a per-file basis. It needs testing, documentation, probably some refactoring, etc, but it's a really convenient thing to have, and has been very useful.

Finishing up the rest of my refactoring now -- Director can just load in VTP files and makes them moveable with a handle widget by default, so that's a really easy way of visualizing the reachability of the arm in various configurations.

---

Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-:-KwayU5_HFZcK3b0MWwJ:b-5njkj1)*

**Comment by manuelli** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ReachabilityAnalyzer/CMakeLists.txt, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhcFWKTX2VsHrm9L6_:-KwejqMwLWSOLLRlfkug:bgmr1o7) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/CMakeLists.txt#L8)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks. Also for the future if you want you can use `target_include_directories` to include directories only for a specific target rather than all targets, which is what `include_directories` does. But LGTM for now.

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KvhdXmJ0oTSbO2V5udO:-Kwelf5f7xyACmuzHPJY:bu6bjg0) ([raw file](https://github.com/robotlocomotion/spartan/blob/835a29c7cbaa247e184ac96dd714589a1bc2bff0/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L165)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Working on this one now, shouldn't be too bad
</blockquote></details>

Ok thanks, let me know when this is finished.

---

*[src/ReachabilityAnalyzer/reachability_analyzer.cpp, line 222 at r4](https://reviewable.io:443/reviews/robotlocomotion/spartan/128#-KwelZJSo65uNoXvriSm:-KwelZJSo65uNoXvriSn:bb1dfxu) ([raw file](https://github.com/robotlocomotion/spartan/blob/8f652c2d6622d0b366a9646cb29005d56d9a30f1/src/ReachabilityAnalyzer/reachability_analyzer.cpp#L222)):*
> ```cpp
>         // configuration
>         // confuses SNOPT sometimes (due to bad gradients at that posture).
>         q0 = model_.getRandomConfiguration(e1_);
> ```

I usually start from the nominal posture that's stored in director. This tends to give pretty decent results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/128)*

**Comment by manuelli** [comment]
Reviewed 1 of 11 files at r1, 8 of 10 files at r4.
Review status: 9 of 18 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/128)*

**Pull request merged**
