### PR TITLE
Basic schunk driver functionality

### PR DESCRIPTION
**Pull request by gizatt**
Verified to work from within Docker (from `iiwaManipApp`) with these changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/138)

### CODE REVIEW

**Comment by manuelli** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 274 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/138#-Kve1bpmv0ceAgGXTlLa:-Kve1bpn5X79EOFfY5KK:b-so3fnm) ([raw file](https://github.com/robotlocomotion/spartan/blob/58ea28f919aa4814068f16b46a2e6232003d902c/CMakeLists.txt#L274)):*
> ```CMake
>     CONFIGURE_COMMAND ""
>     BUILD_COMMAND ${BAZEL_ENV} "${BAZEL}" build //...
>     INSTALL_COMMAND "${CP}" ${build_dir}/externals/drake-schunk-driver/bazel-bin/src/schunk_driver ${build_dir}/install/bin/
> ```

Is this basically just copying from the drake build to our `install/bin` location?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/138)*

**Comment by gizatt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 274 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/138#-Kve1bpmv0ceAgGXTlLa:-KveGHpV_iejx_g7Fo0d:b-1n8w1q) ([raw file](https://github.com/robotlocomotion/spartan/blob/58ea28f919aa4814068f16b46a2e6232003d902c/CMakeLists.txt#L274)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

Is this basically just copying from the drake build to our `install/bin` location?
</blockquote></details>

Yes, this builds with bazel now but I dont think has an install rule yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/138)*

**Comment by manuelli** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 274 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/138#-Kve1bpmv0ceAgGXTlLa:-KveQT8AZ4hfKILd7WCw:b-b8uqsm) ([raw file](https://github.com/robotlocomotion/spartan/blob/58ea28f919aa4814068f16b46a2e6232003d902c/CMakeLists.txt#L274)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Yes, this builds with bazel now but I dont think has an install rule yet
</blockquote></details>

Ok fine with me as an interim solution. I think eventually we should run all these `drake` executables with the `bazel run` type commands (especially if they are using other `bazel` magic to find urdfs etc.) If you could just make an issue in `spartan` to track this I'm happy to merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/138)*

**Comment by manuelli** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/138#-:-KveQp7U2DIrEsQWfCAW:bnfp4nl)*

**Pull request merged**
