### PR TITLE
add command line arg for camera serial number to pybullet sim

### PR DESCRIPTION
**Pull request by manuelli**
Cleans up some code to facilitate different cameras, with min range and max range support.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/245)

### CODE REVIEW

**Comment by gizatt** [comment]
Just one tweak below, otherwise lgtm.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py, line 177 at r1](https://beta.reviewable.io/reviews/robotlocomotion/spartan/245#-L4w5GCc9_nzhJTsLB3h:-L4w5GCc9_nzhJTsLB3i:bnupabe) ([raw file](https://github.com/robotlocomotion/spartan/blob/fef7896d5e1150978c83ca986a8ed9cfb554fd99/src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py#L177)):*
> ```Python
>             self.depth_min_range = info_yaml['depth']['min_range']
>         else:
>             self.depth_min_range = IIWA_CAMERA_MIN_DISTANCE
> ```

I think you mean "IIWA_DEPTH_CAMERA_MIN_DISTANCE"?

---

*[src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py, line 182 at r1](https://beta.reviewable.io/reviews/robotlocomotion/spartan/245#-L4w5J662W80138KrWDE:-L4w5J662W80138KrWDF:b-7ttkwr) ([raw file](https://github.com/robotlocomotion/spartan/blob/fef7896d5e1150978c83ca986a8ed9cfb554fd99/src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py#L182)):*
> ```Python
>             self.depth_max_range = info_yaml['depth']['max_range']
>         else:
>             self.depth_max_range = IIWA_CAMERA_MAX_DISTANCE
> ```

ditto^^

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/spartan/245#-:-L4w60Q71RuqnlPwJSsJ:bhdc7ae)*

**Comment by manuelli** [comment]
Yes good catch. Will fix

**Comment by manuelli** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py, line 177 at r1](https://beta.reviewable.io/reviews/robotlocomotion/spartan/245#-L4w5GCc9_nzhJTsLB3h:-L5A22WDEoAhpY7Fa2Ma:b-896fix) ([raw file](https://github.com/robotlocomotion/spartan/blob/fef7896d5e1150978c83ca986a8ed9cfb554fd99/src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py#L177)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

I think you mean "IIWA_DEPTH_CAMERA_MIN_DISTANCE"?
</blockquote></details>

Done.

---

*[src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py, line 182 at r1](https://beta.reviewable.io/reviews/robotlocomotion/spartan/245#-L4w5J662W80138KrWDE:-L5A234x4PwGFbsjlhUz:b-896fix) ([raw file](https://github.com/robotlocomotion/spartan/blob/fef7896d5e1150978c83ca986a8ed9cfb554fd99/src/catkin_projects/rlg_simulation/scripts/pybullet_iiwa_rlg_simulation.py#L182)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

ditto^^
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/spartan/245)*

**Comment by gizatt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/spartan/245#-:-L5AEGSj9cG08E7v7Pps:bnfp4nl)*

**Pull request merged**
