### PR TITLE
update libbot

### LINKED ISSUE #236: ROS Trajectory Server is broken
Just tested with pr #233, ROS Trajectory Server is broken. Following is the error message from command ```roslaunch robot_control robot_control.launch```:
```
Traceback (most recent call last):
  File "/home/yunzhu/spartan/build/install/lib/robot_control/trajectory_server.py", line 13, in <module>
    from drake import lcmt_iiwa_command, lcmt_iiwa_status ,lcmt_robot_state
  File "/home/yunzhu/spartan/build/install/lib/python2.7/site-packages/drake/__init__.py", line 28, in <module>
    from .lcmt_manipulator_plan_move_end_effector import lcmt_manipulator_plan_move_end_effector
  File "/home/yunzhu/spartan/build/install/lib/python2.7/site-packages/drake/lcmt_manipulator_plan_move_end_effector.py", line 12, in <module>
    import bot_core.position_3d_t
ImportError: No module named position_3d_t
```

### PR DESCRIPTION
**Pull request by manuelli**
fixes #236

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/239)

### CODE REVIEW

**Comment by manuelli** [comment]
@jamiesnape bumping `libbot` is leading to build errors. Looks like it can't find `lcm-python`. Snippet from the build log below

```
16:15:25 [  5%] Building C object CMakeFiles/lcmtypes_bot2-core.dir/lcmtypes/c/lcmtypes/bot_core_image_t.c.o
16:15:25 [  7%] Building C object CMakeFiles/lcmtypes_bot2-core.dir/lcmtypes/c/lcmtypes/bot_core_raw_t.c.o
16:15:25 Scanning dependencies of target bot2-core
16:15:25 -- Found Java: /usr/bin/java (found version "1.8.0.151") 
16:15:25 [ 10%] Building C object src/bot_core/CMakeFiles/bot2-core.dir/set.c.o
16:15:25 -- Found GLib2_glib: /usr/lib/x86_64-linux-gnu/libglib-2.0.so  
16:15:25 -- Found GLib2_gthread: /usr/lib/x86_64-linux-gnu/libgthread-2.0.so  
16:15:25 -- Found GLib2: /usr/lib/x86_64-linux-gnu/libglib-2.0.so  found components:  gthread glib 
16:15:25 -- Detecting CXX compile features - done
16:15:25 CMake Error at python/CMakeLists.txt:26 (message):
16:15:25   Could NOT find lcm-python
```

**Comment by jamiesnape** [comment]
Ok, looking into it.

**Comment by jamiesnape** [comment]
Try the very latest master and pass the `LCM_PYTHON_DIR_HINTS` argument to the libbot external project.

**Comment by manuelli** [comment]
I added the `LCM_PYTHON_DIR_HINTS` argument. This fixed that error but led to another. 

```
[  5%] Performing configure step for 'bot2-lcm-utils'
CMake Error at CMakeLists.txt:46 (message):
  Could NOT find lcm-spy

-- Configuring incomplete, errors occurred!
See also "/home/manuelli/spartan/build/libbot/bot2-lcm-utils/CMakeFiles/CMakeOutput.log".
```

it can't find `lcm-spy`. The error is coming from [here](https://github.com/RobotLocomotion/libbot2/blob/master/bot2-lcm-utils/CMakeLists.txt#L46). It is looking for an executable named `lcm-spy` but I don't think that drake provides that, I think it was changed to be `drake-lcm-spy`. Grep'ing for `lcm-spy` doesn't yield any `lcm-spy` executables in the build, only `drake-lcm-spy`.

```
manuelli@a8c1a70b2af0:~/spartan/build$ find . | grep "lcm-spy"
./install/bin/drake-lcm-spy
./install/share/java/drake-lcm-spy.jar
./install/share/java/lcm-spy.jar

```

**Comment by jamiesnape** [comment]
Looks like you need https://github.com/RobotLocomotion/drake/pull/7802. FYI @fbudin69500.

**Comment by manuelli** [comment]
Ok so it looks like we are blocked until https://github.com/RobotLocomotion/drake/pull/7802 lands.

**Comment by gizatt** [comment]
A clean rebuild with that PR (rebased on Drake master) fails in Director with:

```
...
CMake Warning (dev) at CMakeLists.txt:36 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "cv-utils" links to target "bot2-core-lcmtypes::lcmtypes_bot2-core"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/gizatt/spartan/build/director/src/cv-utils-build
[ 42%] Performing build step for 'cv-utils'
[ 20%] Building CXX object CMakeFiles/cv-utils.dir/multisense_utils/multisense_utils.cpp.o
In file included from /home/gizatt/spartan/build/director/src/cv-utils/multisense_utils/multisense_utils.hpp:16:0,
                 from /home/gizatt/spartan/build/director/src/cv-utils/multisense_utils/multisense_utils.cpp:4:
/home/gizatt/spartan/build/install/include/lcmtypes/bot_core/images_t.hpp:13:32: fatal error: bot_core/image_t.hpp: No such file or directory
compilation terminated.
CMakeFiles/cv-utils.dir/build.make:134: recipe for target 'CMakeFiles/cv-utils.dir/multisense_utils/multisense_utils.cpp.o' failed
make[8]: *** [CMakeFiles/cv-utils.dir/multisense_utils/multisense_utils.cpp.o] Error 1
...
```

**Comment by jwnimmer-tri** [comment]
RobotLocomotion/drake#7802 has landed.

**Comment by manuelli** [comment]
Ok I just bumped the `drake` revision. Let's see if the build passes this time or if we error out with the problem that @gizatt mentioned.

**Comment by manuelli** [comment]
Looks like we are still having the same build error that Greg got. Looks like the `cv-utils` target of director links to target `bot2-core-lcmtypes::lcmtypes_bot2-core` but this isn't being found. I believe that `drake` is still providing `bot2-core-lcmtypes::lcmtypes_bot2-core` even though it doesn't supply `libbot` anymore. Is this correct @jamiesnape?

```
19:26:14 
19:26:14   Target "cv-utils" links to target "bot2-core-lcmtypes::lcmtypes_bot2-core"
19:26:14   but the target was not found.  Perhaps a find_package() call is missing for
19:26:14   an IMPORTED target, or an ALIAS target is missing?
```

This eventually leads to the error 

```
19:26:17 In file included from /home/jenkins/spartan/build/director/src/cv-utils/multisense_utils/multisense_utils.cpp:4:0:
19:26:17 /home/jenkins/spartan/build/director/src/cv-utils/multisense_utils/multisense_utils.hpp:15:31: fatal error: lcmtypes/bot_core.h: No such file or directory
```

**Comment by jamiesnape** [comment]
Drake provides `bot2-core-lcmtypes::lcmtypes_bot2-core-cpp`. Can `cv-utils` use the C++ version of the lcmtypes?

**Comment by manuelli** [comment]
Ok we can look into that. @patmarion what would be the work involved for moving to the C++ version of the lcmtypes. Just so I understand what happened here to break the director build, did `drake` previously provide `bot2-core-lcmtypes::lcmtypes_bot2-core` and this was lost when `libbot` was removed?

**Comment by jamiesnape** [comment]
Yes, we stopped providing the C version. We used to provide both C and C++, but Drake never used the C version.

**Comment by jamiesnape** [comment]
From a quick look at director, I only see C++ usage, so maybe `cv-utils` needs both, but director is only using part of it? If so, it probably would not be too hard, but I have not looked too closely as to why `cv-utils` would need both.

**Comment by manuelli** [comment]
So `cv-utils` is an external project https://github.com/patmarion/cv-utils. I am looking through the code now, it should be pretty trivial to change it over to use the C++ types. I will give it a try when I get a few minutes.

**Comment by manuelli** [comment]
I made the appropriate changes and it built fine on my machine. Just pushed the updates to see if it passes CI. If so I will PR the changes against `cv-utils` and `director`

**Comment by gizatt** [comment]
Jenkins please test

**Comment by gizatt** [comment]
OK, not a good idea...

The issue I was curious about was that Jenkins only uses `git submodule update --init`, but the submodule changes you've made go two layers deep. I don't know enough about how `git submodule update` works to know if `--recursive` is needed for that to work.

**Comment by gizatt** [comment]
Jenkins please test

(Trying some changes to ensure Jenkins nukes the workspace and pulls it down clean, which ought to also circumvent that issue)

**Comment by manuelli** [comment]
Yeah I had to change teh `.gitmodules` to point it to my `director` branch. I think

```
git submodule init
git submodule update
```

should be sufficient.

**Comment by gizatt** [comment]
I'm wrong about the nested submodule thing -- `cv-utils` an ExternalProject within director, so Jenkins is definitely doing the right thing at the top level.

I'm not convinced that your changes to cv-utils are sufficient yet -- you change the linking, but it looks like some files still try to include the C lcmtypes.

**Comment by manuelli** [comment]
Yeah, it is failing on including `lcmtypes/bot_core.h` this may need to be changed to `lcmtypes/bot_core.hpp`. I am trying to figure out why it built for me locally.

**Comment by gizatt** [comment]
I have the appropriate diff to fix, pushing it up somewhere useful

**Comment by gizatt** [comment]
At last!

**Comment by manuelli** [comment]
Looks like https://github.com/RobotLocomotion/director/pull/582 landed. I just updated the branch to point to that. As soon as CI finishes we should be ready to merge.

**Pull request merged**
