### PR TITLE
Bring in all handical, fusion, etc updates, on reverted master

### PR DESCRIPTION
**Pull request by peteflorence**
After https://github.com/RobotLocomotion/spartan/pull/268

This is like the 5th attempt on merging most of this code :)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/269)

### CODE REVIEW

**Comment by peteflorence** [comment]
Looks like this isn't passing simulation test?

**Comment by manuelli** [comment]
I am building this locally and will investigate.

**Comment by peteflorence** [comment]
Hey @manuelli 

I just realized

This branch doesn't have the revert commits

**Comment by peteflorence** [comment]
This was superceded by #273

**Pull request closed without merging**
