### PR TITLE
Update to drake/master

### PR DESCRIPTION
**Pull request by manuelli**
This PR updates `drake` to master. This is necessary due to some checksum issues when downloading one of drake's externals `sdformat`. Unfortunately this has broken the `RemoteTreeViewer` build, see #224.

- Fixes to account for the new naming convention in drake from `//drake/examples/kuka_iiwa_arm` to `//examples/kuka_iiwa_arm`. These changes are in the `iiwa_hardware.pmd` file. I also had to change `DRAKE_RESOURCE_ROOT` to be the parent folder of drake.

This isn't a pretty PR but I do think it needs to be merged ASAP since the current `drake` sha doesn't build.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/225)

### CODE REVIEW

**Comment by gizatt** [comment]
This looks fine as it is -- I expect the DRAKE_RESOURCE_ROOT change to break some of my sim stuff, but what is breaks was a temp hack anyway, so I don't take any offence. I'm building a version of this now to see if I can fix the RemoteTreeViewer build issue -- it looks relatively simple, like a `FindPackage(BOOST)` should solve it. But if you want to merge as-is no major functionality is lost with that stuff being disabled for now.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[config/setup_environment.sh.in, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/225#-L1Yq-KpakmOK9FoHN1h:-L1Yq-KpakmOK9FoHN1i:b-3azhf6) ([raw file](https://github.com/robotlocomotion/spartan/blob/4a41e6fdbbe12d5c71a17748b3441a1f014059a9/config/setup_environment.sh.in#L4)):*
> ```
> export SPARTAN_BUILD_DIR=@CMAKE_BINARY_DIR@
> export SPARTAN_INSTALL_DIR=@CMAKE_INSTALL_PREFIX@
> export DRAKE_RESOURCE_ROOT=@CMAKE_BINARY_DIR@/install/share/drake
> ```

What's the story behind this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/225#-:-L1YqNntCPd5mDZc8KXa:b-9aq8xg)*

**Comment by manuelli** [comment]
I'm happy to wait for this DRAKE_RESOURCE_ROOT issue to be resolved.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[config/setup_environment.sh.in, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/225#-L1Yq-KpakmOK9FoHN1h:-L1Yr7QFTVHY3QmkvNza:b-ghs3fs) ([raw file](https://github.com/robotlocomotion/spartan/blob/4a41e6fdbbe12d5c71a17748b3441a1f014059a9/config/setup_environment.sh.in#L4)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

What's the story behind this change?
</blockquote></details>

1) some drake convention was changed so it needs to point to the folder containing drake rather than drake itself.
2) I pointed this to the source tree (rather than the build tree) So now if you modify a data file in the source tree then relaunch your executable it will find that file. This way you avoid having to rebuild to have that change be reflected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/225#-:-L1YrTDaIktKDlqr_Gdi:b-c7srkn)*

**Comment by gizatt** [comment]
The sim stuff only exists on a branch of mine (shouldn't break anything in master yet), so no need to block on it. I'll keep you posted on the RemoteTreeViewer fix.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[config/setup_environment.sh.in, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/225#-L1Yq-KpakmOK9FoHN1h:-L1YrxX6z37QVF-41pbn:b-moijao) ([raw file](https://github.com/robotlocomotion/spartan/blob/4a41e6fdbbe12d5c71a17748b3441a1f014059a9/config/setup_environment.sh.in#L4)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

1) some drake convention was changed so it needs to point to the folder containing drake rather than drake itself.
2) I pointed this to the source tree (rather than the build tree) So now if you modify a data file in the source tree then relaunch your executable it will find that file. This way you avoid having to rebuild to have that change be reflected.
</blockquote></details>

That sounds strictly better than how it was before... I believe everything of mine it has the potential to break lives in a branch of mine, so merging this shouldn't break anything outwardly visible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/225#-:-L1YqrIFKTuKqIQVH1Oc:b-1et37v)*

**Comment by manuelli** [comment]
Sorry I mean to say I am happy to wait for the RemoteTreeViewer stuff to get fixed. I am adding some more utilities for the optitrack stuff in the meantime.

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/225#-:-L1YuzhV-BqAxQi6To_M:bsf67qg)*

**Comment by manuelli** [comment]
Given that the RemoteTreeViewer issue doesn't seem like it's going to be a trivial fix I am going to go ahead and merge this.

**Pull request merged**
