### PR TITLE
Fix deprecated usages of RigidBodyTree::bodies

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Requires https://github.com/RobotLocomotion/director/pull/595

See robotlocomotion/drake#8085 for more info.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/257)

### CODE REVIEW

**Comment by gizatt** [comment]
jenkins please test

could have sworn you were already whitelisted...

**Comment by EricCousineau-TRI** [comment]
@gizatt It seems like there may be a copy of `drake`s `install_prereqs.sh` floating around somewhere? CI reported this error:

```
15:16:52 See also "/home/jenkins/spartan/build/drake/CMakeFiles/CMakeOutput.log".
15:16:52 CMakeFiles/drake.dir/build.make:106: recipe for target 'src/drake-stamp/drake-configure' failed
15:16:52 Extracting Bazel installation...
15:16:52 CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
15:16:52   Could NOT find Bazel: Found unsuitable version "0.6.1", but required is at
15:16:52   least "0.9.0" (found /usr/bin/bazel)
15:16:52 Call Stack (most recent call first):
15:16:52   /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
15:16:52   cmake/modules/FindBazel.cmake:31 (find_package_handle_standard_args)
15:16:52   CMakeLists.txt:18 (find_package)
15:16:52 
```

Would it be possible to make Spartan's prereqs use Drake's prereqs scripts directly? (Is there something that messes up y'all's workspace?)

**Comment by manuelli** [comment]
We do use the `drake` prereqs I believe. See [here](https://github.com/RobotLocomotion/spartan/blob/master/setup/docker/spartan.dockerfile#L30)

**Comment by gizatt** [comment]
Ditto from lucas -- maybe it could be the sharing of the bazel artifact dir
between builds? That piece of the build isn't blown away between CI runs, I
think. (It probably should be...)

**Comment by EricCousineau-TRI** [comment]
Ah, gotcha! My bad!

> (It probably should be...)

For `drake` we have `unprovisioned` build images for PRs that change dependencies; do y'all have any flavors of that?
It may slow your CI testing a bit to have all builds be unprovisioned... But if you do switch up your deps quite a bit, then mayhaps?

**Comment by jwnimmer-tri** [comment]
None of that is relevant.  The actual problem is this, from the CI log:
```
15:16:41  ---> Running in 99eba751fd43
15:16:42 /tmp/drake_install_prereqs.sh: line 25: /tmp/binary_distribution/install_prereqs.sh: No such file or directory
```

**Comment by EricCousineau-TRI** [comment]
Ahhh, good catch! Will see if I can briefly mend that in this PR.

**Comment by manuelli** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/257#-L61zSXn9iJw-h7wKPEw:-L61zSXn9iJw-h7wKPEx:bb9rwxd) ([raw file](https://github.com/robotlocomotion/spartan/blob/4e4ababcf6d563c04b4bbf9ed08b063cea4ea84e/.gitmodules#L4)):*
> ```
> 	path = director
>     # PR DRAFT(eric.cousineau): Update this once upstream PR lands.
> 	url = https://github.com/EricCousineau-TRI/director.git
> ```

Ok for now. But would like to hold off on merging this until the director PR lands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/257)*

**Comment by manuelli** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/257#-L61zSXn9iJw-h7wKPEw:-L62-BN3OB8iGjf91alg:b-jod11s) ([raw file](https://github.com/robotlocomotion/spartan/blob/4e4ababcf6d563c04b4bbf9ed08b063cea4ea84e/.gitmodules#L4)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

Ok for now. But would like to hold off on merging this until the director PR lands.
</blockquote></details>

Actually just checked director and that PR landed. Can you update the submodule url and bump the director sha. Then I am happy to merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/257)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/spartan/257#-L61zSXn9iJw-h7wKPEw:-L62FOZrHoUisuiQtQoj:b-896fix) ([raw file](https://github.com/robotlocomotion/spartan/blob/4e4ababcf6d563c04b4bbf9ed08b063cea4ea84e/.gitmodules#L4)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

Actually just checked director and that PR landed. Can you update the submodule url and bump the director sha. Then I am happy to merge.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/257)*

**Comment by manuelli** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/257)*

**Pull request merged**
