### PR TITLE
Replace our schunk meshes with Drake's

### PR DESCRIPTION
**Pull request by gizatt**
Drake has more up-to-date and accurate meshes for the WSG 50 -- this PR drops our independent (and old) meshes for it, and replaces the references with references into Drake's version.

The most far-reaching change is that the `palm` link is now called `wsg_50_base_link`. I tried to make sure things are lined up and that its position has not changed relative to the robot, but I'm not 100% sure of that yet -- this needs some robot testing to see how it does.

Still broken in terms of #178, but PRing for opinions on whether this is the right tactic for getting the appropriate meshes in place. (I think it is reasonable -- we may make modification to our gripper, but only in terms of mounting new things on it. If we ever mount new fingers, we'll want to undo this, but till then, TRI maintains a good set of models for us.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/207)

### CODE REVIEW

**Comment by manuelli** [comment]
Lets do some on robot testing of this and then merge it if we are happy.

**Comment by gizatt** [comment]
This now works as well as I can tell on the robot. RVIZ and Director both visualize finger states quite happily:

image
image

The `palm` link is no more (as I'm relying on Drake's meshes and hand setup, but they removed it...), but I have added a ghost link called 'wsg_50_old_palm` that is a drop-in replacement, to avoid headache converting things like the configuration scripts. As such, calibrations should carry over precisely (and do, as far as I can tell).

**Comment by manuelli** [comment]
Ok I resolved the merge conflict in `pub_joint_state.py`. I will run a final local test and then this should be good to merge.

**Comment by gizatt** [comment]
Is this good to merge?

**Comment by manuelli** [comment]
Fine with me. Go ahead and merge once the build passes.

**Pull request merged**
