### PR TITLE
updates for kuka_sim_wsg using spartan

### PR DESCRIPTION
**Pull request by manuelli**
- refactors the kuka_iiwa_state_translator to handle both sim and hardware use cases.
- create new urdf and director_config that match what is used in the drake sim. Only difference is gripper mount position.

### CODE REVIEW

**Comment by sammy-tri** [comment]
I've been using the old version with the sim for a while.  Out of curiosity, what made you need to use IIWA_STATE_EST instead of IIWA_STATUS?

**Comment by sammy-tri** [comment]
Mismatched URDFs was not a reason I had considered.  (I'm not objecting to merging this, fwiw)

**Comment by sammy-tri** [comment]
(to clarify my previous comment, I do understand it's not feasible to create the world in director the same way that iiwa_wsg_simulation does from separate urdf and SDF files)

**Comment by patmarion** [comment]
If I'm not mistaken, `IIWA_STATUS` has the positions of the 7 arm joints only.  `IIWA_STATE_EST` includes the pose of the base (positioned on a table).

**Pull request merged**
