### PR TITLE
Fusion server upgrades, can now perform fusion

### PR DESCRIPTION
**Pull request by peteflorence**
Remaining list before this can merge:

- [x] Resolve opencv conflict with Director (easiest to just remove the weak OpenCV dependency)
- [ ] Auto-output pointcloud and exit ElasticFusion (merge this feature from LabelFusion branch)

Here is what this PR does:

1) Removes the previous way of incorporating ElasticFusion into spartan, which was building everything during docker_build and rebuilding a whole version of director.  Now ElasticFusion is a submodule, which can be built by just './build.sh' inside 'src/ElasticFusion'

2) The fusion server can be started with:

```
use_ros && use_spartan && ./spartan/src/catkin_projects/fusion_server/scripts/capture_fusion_data_server.py
```

3) There are three basic component ROS services it provides:

- `StartBaggingFusionData`,
- `StopBaggingFusionData`, and
- `PerformElasticFusion`

There is also a fourth service that uses all three of the above, together with moving the arm:

- `CaptureSceneAndFuse`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/223)

### CODE REVIEW

**Comment by gizatt** [comment]
Cool! Does the Director opencv conflict arise during build, or when running this?

You can see about getting CI coverage by editing `spartan/setup/docker/run_jenkins.sh` and adding the appropriate lines to get ElasticFusion built. (It's a regular bash script, but with extra handling of error conditions output by every step it performs, s.t. it returns nonzero if any of its steps fail, and also outputs slightly-helpful diagnostic errors where possible.)  Up to you if you want to include it in this PR, or I can help get it in later

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/docker/install_dependencies.sh, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/223#-L0vMthcZy2g6UoCqfuj:-L0vMthcZy2g6UoCqfuk:bmfq6yr) ([raw file](https://github.com/robotlocomotion/spartan/blob/caa762955fb1fa318f61e836fb76f205489b109b/setup/docker/install_dependencies.sh#L19)):*
> ```Shell
>   usbutils \
>   dialog \
>   python-pip \
> ```

I assume this just works anyway, but this backslash looks errant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/223#-:-L0vNtBaITQMrxIWY8Zk:bjy2hh3)*

**Comment by peteflorence** [comment]
Thanks Greg.

There is a runtime issue for director with opencv.  I am testing out master
now to make sure it's not happening in master.

**Comment by peteflorence** [comment]
Running into Drake sdformat issues, won't be able to resolve this tonight

**Comment by peteflorence** [comment]
YunZhu and I want to merge this.

There are no build conflicts, we just tested the fusion.

The only thing haven't done is finish the API of sending data back out of ElasticFusion.

The reason not doing it now is because PointCloud2 is not actually sufficient for what YunZhu wants, so will need to spend more time on it.

**Pull request merged**
