### PR TITLE
Major calibration updates: use handical, chessboard visualizer, new poses, and includes...

### PR DESCRIPTION
**Pull request by peteflorence**
... great calibration params for Kuka 1

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/261)

### CODE REVIEW

**Comment by manuelli** [comment]
The build failed since the build server doesn't have access to the `handical` repo. Currently only @peteflorence and I have access. Will ping @RussTedrake about this.

**Comment by manuelli** [comment]
Reviewed 6 of 9 files at r1, 4 of 8 files at r2, 1 of 2 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.gitmodules, line 46 at r4](https://reviewable.io:443/reviews/robotlocomotion/spartan/261#-L68JnfqwcQxw6TbnPl-:-L68JnfrpfVTKn1OEClm:b-mqo5y4) ([raw file](https://github.com/robotlocomotion/spartan/blob/aaf4661925afc46a9f82ee2c2c87bfc383782d8c/.gitmodules#L46)):*
> ```
> [submodule "src/handical"]
> 	path = src/handical
> 	url = git@github.com:ToyotaResearchInstitute/handical.git
> ```

we will need to update this to be somwhere that everyone in RLG has access to.

---

*[modules/spartan/calibration/handeyecalibration.py, line 804 at r4](https://reviewable.io:443/reviews/robotlocomotion/spartan/261#-L68KLw2UsILnAdbd1oe:-L68KLw2UsILnAdbd1of:bhx7syz) ([raw file](https://github.com/robotlocomotion/spartan/blob/aaf4661925afc46a9f82ee2c2c87bfc383782d8c/modules/spartan/calibration/handeyecalibration.py#L804)):*
> ```Python
>             pose = np.asarray([ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
>        -0.68  ,  1.0    , -1.688 ,  1.0    ,  -0.5635,  1.0    ])
>             ikPlanner.addPose(pose, startPoseName)
> ```

Did adjusting the seedPose actually end up giving the desired result? I thought we tested it and it didn't work. I was under the impression that you directly modified the joint angles and added 180 degrees to joint 7?

---

*[setup/docker/entrypoint.sh, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/spartan/261#-L68Kk83V1m0E7RlXhAU:-L68Kk83V1m0E7RlXhAV:bvcleao) ([raw file](https://github.com/robotlocomotion/spartan/blob/aaf4661925afc46a9f82ee2c2c87bfc383782d8c/setup/docker/entrypoint.sh#L25)):*
> ```Shell
> 	export PYTHONPATH=$PYTHONPATH:$GTSAM_INSTALL_DIR/cython
>     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GTSAM_INSTALL_DIR/lib
>     export PYTHONPATH=$PYTHONPATH:$SPARTAN_SOURCE_DIR/src/handical/build/cython/handical
> ```

we might want to thrown an error if $SPARTAN_SOURCE_DIR is empty. Not critical but a nice safety feature.

---

*[src/catkin_projects/station_config/RLG_iiwa_1/hand_eye_calibration/carmine_1.yaml, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/spartan/261#-L68L3o3XkeLmuIWzoQQ:-L68L3o3XkeLmuIWzoQR:btbs6kj) ([raw file](https://github.com/robotlocomotion/spartan/blob/aaf4661925afc46a9f82ee2c2c87bfc383782d8c/src/catkin_projects/station_config/RLG_iiwa_1/hand_eye_calibration/carmine_1.yaml#L36)):*
> ```YAML
>   rgb: "bgr8"
> 
> filename_extension: "jpg"
> ```

Did this end up mattering? As long as it's working with jpg I'm fine with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/261)*

**Comment by peteflorence** [comment]
Thanks for reviewing

Re: bmp or jpg, the current calibration used jpg, but expect it wasn’t the
issue and bmp is fine.

And yes I actually got the iKPlanner to solve for  inverted poses. There
was a couple things that helped here. One is that every other attempted
computed pose is flipped, but some return info 13 (I think that is one type
of fail?).  Additionally the voxel grid filter filters out many computed
poses so the actual poses for the robot are not every other flipped. I also
added a couple other changes to a couple other joints, not just 7th. In the
end it is the case that about half of the currently used poses are flipped
on 7th joint.

The main improvement opportunity for computing poses would be to use the
slight angle of the mount in the initial guess.

But given that calibration is working well now I would prefer to not change
anything

**Comment by manuelli** [comment]
Ok I'm satisfied. Happy to merge as soon as the handical repo issue is resolved.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/261#-:-L68XPfkLmH_BHmZFEVs:b-k33obu)*

**Pull request closed without merging**
