### PR TITLE
Repoint to kuka_driver.cc that publishes ROS

### PR DESCRIPTION
**Pull request by peteflorence**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/215)

### CODE REVIEW

**Comment by peteflorence** [comment]
Should potentially also get rid of python joint publisher from Start ROS script

**Comment by peteflorence** [comment]
@manuelli would like your opinion on best refactor of procman before we merge

**Comment by manuelli** [comment]
So in the past we have had a completely separate procman for simulation, basically `iiwa_sim.pmd`. I would vote to moving to that format, even though it requires a bit of work to keep the two in sync.

**Comment by manuelli** [comment]
I think once we fix the procman stuff I would be happy to merge this. @peteflorence

**Comment by peteflorence** [comment]
OK this is good to go.

I opted for one-pmd-file, I think it was just easier to move the LCM-->ROS translator up into the sim group.

**Comment by gizatt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/215#-:-L0usfn3fu75gb4LO6rq:bnfp4nl)*

**Pull request merged**
