### PR TITLE
kPAM experiment code

### PR DESCRIPTION
**Pull request by manuelli**
Don't merge, on robot testing needed.

Updates used in the kPAM experiments. Supersedes #374 

- adds lots of useful functionality to grasp_supervisor.py
- updates to CUDA 10, and nvidia-docker2

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/375)

### CODE REVIEW

**Comment by manuelli** [comment]
This is working on my local machine but the CI is failing. Probably due to nvidia-docker2 issue. @gizatt lets discuss in person

**Comment by gizatt** [comment]
Jenkins please test

(Current issue was that Jenkins was missing python yaml for the docker run script. Also, you'll need to fix the merge conflicts probably?)

**Comment by manuelli** [comment]
This has been tested on the robot. Ran the full kPAM demo with no issues. Will resolve build issues and then it is ready for review and merge.

**Comment by manuelli** [comment]
All the tests passed locally on my machine. So could be an nvidia-docker2 related issue. Will follow up with @gizatt

**Comment by gizatt** [comment]
I don't know what's up with the current build -- the previous one built just fine but failed in testing, which I'm happy to chalk up to e.g. the nvidia-docker2 issue probably causing some X or other display bugs that broke the sim. I'll drag Jenkins to class today and see what I can do, but I'm OK with merging this without a full build server pass considering it's built successfully and tests fine. Will get a review pass during class too.

**Comment by gizatt** [comment]
Jenkins please test

**Pull request merged**
