### PR TITLE
Adds a terminator config file to the docker

### PR DESCRIPTION
**Pull request by gizatt**
With default coloring of red background, which distinguishes it from the black background
of the default terminatorconfig on iiwa-workstation

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/136)

### CODE REVIEW

**Comment by peteflorence** [comment]
Initial user testing suggests a calmer color than red would be preferred.

Maybe a dark, soft blue like this? https://www.google.com/imgres?imgurl=http%3A%2F%2Fi.imgur.com%2FkxQ6tcC.png&imgrefurl=http%3A%2F%2Fzachwhaleys.website%2F2017%2F01%2F19%2Fsolarized%2Btmux%2Bls%2Bboldtext%2F&docid=DVSOACpMkMk40M&tbnid=06uSLvOJL2KcbM%3A&vet=10ahUKEwiYlrfY89fWAhVl9IMKHa19BTMQMwhYKCcwJw..i&w=848&h=597&bih=1437&biw=2495&q=terminator%20config%20color&ved=0ahUKEwiYlrfY89fWAhVl9IMKHa19BTMQMwhYKCcwJw&iact=mrc&uact=8

**Comment by gizatt** [comment]
It's not exactly that style because the text colors are complicated, but how's this?

image

**Comment by peteflorence** [comment]
LGTM

**Comment by manuelli** [comment]
LGTM

**Pull request merged**
