### PR TITLE
updates to grasp_supervisor

### PR DESCRIPTION
**Pull request by manuelli**
Tested on robot.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/355)

### CODE REVIEW

**Comment by peteflorence** [comment]
Is this ready for code review?

**Comment by manuelli** [comment]
Yes, ready for review. Might be a bit messy, but grasp_supervisor is sort of our sandbox code anyways.

**Comment by peteflorence** [comment]
:+1: 

looking at close-up fusion first

**Comment by manuelli** [comment]
@peteflorence #353 has been merged. So this should be ready for revew.

**Comment by manuelli** [comment]
@peteflorence, @gizatt  I would like to get this merged. I don't like to have long-living branches.

**Comment by manuelli** [comment]
ok will wait for build to finish and then merge.

**Pull request merged**
