### PR TITLE
Cleanup IIWA urdfs, and build all of Drake (to prepare to build up a more mature sim environment)

### PR DESCRIPTION
**Pull request by gizatt**
Looking for feedback on this way of cleaning up some URDF's, and also invoking Drake's sim backend (and general controller) executables.

Brief changes:
- Changed build to build all of Drake, instead of just the install target, so that other executables (like kuka wsg sim) can be used by Spartan without requiring Drake build tweaks.
- Removes most of Spartan's IIWA and Schunk meshes and URDFs, pointing the depending programs to Drake's versions.
- Remove the specialized IIWA sim interface drake-visualizer script, as it shouldn't be that different from the real interface.
- gitignore for snopt.out files

I focused on removing URDFs and mesh files in Spartan that already existed in Drake (in what looks like more-mature formats). I think we'll wind up populating Spartan with some of our own models of our own fixtures, manipulands, and robot configurations, but Drake looks like it has good version of the IIWA and Schunk models, which we don't really need to replicate. A better personal understanding of Director's ability to glue together models (e.g. put arbitrary urdfs together into robot systems) would help me with this cleanup too, as the surviving URDF is the one that glues the IIWA and Schunk together. We ought to unify our approach to generating robot configurations for use in visualization / performing IK / whatever.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/131)

### CODE REVIEW

**Comment by sammy-tri** [comment]
I definitely like the idea of not reproducing URDFs between drake and spartan.  FWIW, I don't think director can glue together models now, so we might have to tackle that one another time.

:+1: from me.

**Comment by patmarion** [comment]
I don't work with the kuka robot anymore so please feel free to re-organize the urdfs however it helps your project.

a bit of background- the reason spartan duplicates the urdf and the python scripts is because, at the time, the stuff in drake was maintained as a example program but not a development/sandbox area, and did not have urdf files that were compatible with the hardware (matching the gripper mounting plate and mount angle).  My suggestion at the time was to use xacro to generate urdf files suitable for the various hardware and sim configurations, but i'm sure there are many possible solutions.  an issue with stitching together urdfs are runtime is that, at the time, the sim stitched together pieces using hardcoded fixed frames, but this posed a problem because the urdf needed to be loaded in at least 3 places: the sim, the visualizer, and the ik engine.

**Comment by manuelli** [comment]
Review status: 0 of 68 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[apps/iiwa/iiwa_sim.pmd, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/spartan/131#-KvhffOWnNctz3teVKGu:-KvhffOWnNctz3teVKGv:b-jlnb48) ([raw file](https://github.com/robotlocomotion/spartan/blob/8dfcf3f3dc55d2b2a101cf6e2bfa3190f91ae876/apps/iiwa/iiwa_sim.pmd#L4)):*
> ```
> 
>   cmd "0.kuka_simulation" {
>     exec = "$SPARTAN_SOURCE_DIR/drake/bazel-bin/drake/examples/kuka_iiwa_arm/kuka_simulation";
> ```

Is there a way to run this with `bazel run`. We should only be using supported drake functionality for running executables. We don't want to be rooting around in some random build directory because if they later change some implementation detail this will break.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/131)*

**Comment by manuelli** [comment]
Review status: 0 of 68 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[apps/iiwa/iiwaManipApp.py, line 209 at r3](https://reviewable.io:443/reviews/robotlocomotion/spartan/131#-Kvhfx1zv0-2EAWFjO-x:-Kvhfx1zv0-2EAWFjO-y:b408w8v) ([raw file](https://github.com/robotlocomotion/spartan/blob/8dfcf3f3dc55d2b2a101cf6e2bfa3190f91ae876/apps/iiwa/iiwaManipApp.py#L209)):*
> ```Python
> def setGripperJointPositions(robotModel, pos):
>     robotModel.model.setJointPositions(
>         [-pos, pos],
> ```

Was this just wrong before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/131)*

**Comment by sammy-tri** [comment]
Review status: 0 of 68 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[apps/iiwa/iiwa_sim.pmd, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/spartan/131#-KvhffOWnNctz3teVKGu:-Kvhh1T1QIIhvgZFhNqe:bbd9h98) ([raw file](https://github.com/robotlocomotion/spartan/blob/8dfcf3f3dc55d2b2a101cf6e2bfa3190f91ae876/apps/iiwa/iiwa_sim.pmd#L4)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

Is there a way to run this with `bazel run`. We should only be using supported drake functionality for running executables. We don't want to be rooting around in some random build directory because if they later change some implementation detail this will break.
</blockquote></details>

Where did we get the idea that `bazel run` was the only supported way to run executables compiled by drake?  (also I think the argument to`bazel run` will always map directly to the path in `bazel-bin` for nearly all targets)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/131)*

**Comment by manuelli** [comment]
Review status: 0 of 68 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[apps/iiwa/iiwa_sim.pmd, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/spartan/131#-KvhffOWnNctz3teVKGu:-KvhhvnPthy3YLWeMoFU:b-5gxqdg) ([raw file](https://github.com/robotlocomotion/spartan/blob/8dfcf3f3dc55d2b2a101cf6e2bfa3190f91ae876/apps/iiwa/iiwa_sim.pmd#L4)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Where did we get the idea that `bazel run` was the only supported way to run executables compiled by drake?  (also I think the argument to`bazel run` will always map directly to the path in `bazel-bin` for nearly all targets)
</blockquote></details>

I formed this opinion of `bazel run` just from monitoring slack conversations and from what Russ had mentioned to me in a slack thread. I basically want to know what is the public API that `drake` uses and only use that. I don't want to update the `drake` submodule and find that things suddenly don't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/131)*

**Comment by manuelli** [comment]
@jwnimmer-tri could you chime in on the right way to run `drake` executables and access `drake` provided URDFs is? I am very inexperienced with `bazel`, but I believe that `bazel run` is the right way to run executables. I am not sure about accessing resources like urdfs. We can't use anything like `getDrakePath()` since `director_config.json` wants an absolute path specified in a text file.

**Comment by jwnimmer-tri** [comment]
Yes, will do.  But I'm in meetings and transit, probably will be tomorrow AM when I can give it a good attention span.

**Comment by jwnimmer-tri** [comment]
> @jwnimmer-tri could you chime in on the right way to run drake executables and access drake provided URDFs?

In this PR, the `BUILD_COMMAND` for Bazel is changed to be:
```bash
${BAZEL_ENV} ${BAZEL} build ${BAZEL_ARGS} //... //:install
```

Indeed as stated, that builds everything that Drake has to offer.  Later, for build speed, you might consider narrowing `//...` to be only certain package trees instead of all of them (e.g. only `"//drake/manipulation/..."` and some examples), but for now the `//...` proposal seems like a good compromise to achieve "set it and forget it", for the cost of longer compilation time.

---

In this PR, the pmd configs are also changed to use, for example:
```bash
exec = "$SPARTAN_SOURCE_DIR/drake/bazel-bin/drake/examples/kuka_iiwa_arm/kuka_simulation";
```

This is probably fine -- you don't _always_ need to use `bazel run` (and indeed, sometimes you should _not_ use `bazel run`).  Using the `bazel-bin` path is supported, but I should explain the why and how for clarity.  There are two relevant questions: (1) will the binary be present and correctly compiled with respect to its source code and dependencies, and (2) will the binary be able to load the data resources that it may need.

---

On (1) Will the binary be present and correctly compiled with respect to its source code and dependencies?

Because the CMakeLists has run `${BAZEL_ENV} ${BAZEL} build ${BAZEL_ARGS} //...` successfully, we know the entire Drake build will have run to completion without any errors, and thus this question resolves to "Yes".  Ways that it could revert back to "No" might be:
- (a) if Drake's source code changes and the build command has not been re-run;
- (b) if the host system changes (e.g., libglib-dev was upgraded via Ubuntu) and the build command has not been re-run;
- (c) if someone manually invokes `bazel build` or `bazel test` or `bazel run` or etc. with different parameters than the CMakeLists build command -- because the CMakeLists carefully controls the BAZEL_ENV and BAZEL_ARGS settings, any manual invocation of any bazel command must match those two settings exactly; failure to do so will result in unsupported behavior;
- (d) assuming BAZEL_ENV and BAZEL_ARGS _do_ match the CMakeLists values, if for example we run, e.g., `bazel build //drake/manipulation/...` then only the manipulation targets will be guaranteed to be correctly compiled -- a program under, e.g., `bazel-bin/drake/examples/kuka_iiwa_simulation/foo` might _no longer be valid_, even if no example source code has changed in the meantime(!); for running binaries out of the source build, the best practice is to run a _single_ bazel build command that lists _all_ the targets you want to use -- if they were unchanged it will be fast (cached), and then you'll know 100% that they are ready to run.

In short: try to avoid running Bazel by hand -- endeavour to have CMakeLists invocations of Bazel be the only place(s) that do it.

---

On (2) Will the binary be able to load the data resources that it may need?

In Spartan's `config/setup_environment.sh.in`, you have:
```bash
export DRAKE_RESOURCE_ROOT=@CMAKE_BINARY_DIR@/install/share/drake
```

Assuming Spartan's instructions have developers sourcing that file, then all Drake binaries will look into the install tree for their data resources and should robustly find them (this is supported config, and tested in Drake's CI).

You will want to be slightly careful because you have two copies of the files on disk now -- the copy in Drake's source tree, and the copy in the install tree.  If you have the env var set, it will always be preferred over anything else, so you should reliably get the copy from the install tree.  So if you edit a file in Drake's source tree, and then build and run, e.g., `$SPARTAN_SOURCE_DIR/drake/bazel-bin/drake/examples/kuka_iiwa_arm/kuka_simulation`, it will use the fresh build of the binary, but the older (installed copy) of the data.  If this ends up as a pain point, I have ideas we could try to mitigate it, so ping me.

Note that if you used an installed copy of the binaries, you would still be managing two copies (source vs installed for both binaries and data), but it would at least be consistent -- if you are running the installed binary, it would at least match its resources, even if you forgot to run the install target.  Conceivably, this would be less confusing to developers.

---

Slightly off-topic but mostly related, be aware of RobotLocomotion/drake#6996.

We are going to remove the word "drake" from all of Drake's package names (the token after `//` in a label), which means that `$FOO/bazel-bin/drake/examples/kuka_iiwa_arm/kuka_simulation` will turn into `$FOO/bazel-bin/examples/kuka_iiwa_arm/kuka_simulation`.  Across this transition, I'll be in touch to make sure we stay in sync.  Either I'll deprecate but not remove the old paths (so that both paths work during a transition period), or if that's unworkable I'll make the flag day as succinct and possible and coordinate with Spartan for least disruption.

Notably, the installed path to binaries will not be affected by this change.  So if you choose to center your development around the installed copy instead of the bazel-bin copy, you will be isolated from this event.

---

Given all of the above, another route you might consider is having Drake install the additional binaries you want that we aren't right now.  If the only challenge is that they aren't present our current draft of the install, then it might be a good solution.  If you instead want to have the Drake submodule locally editable with convenient turn-around (without going through the full build & install step), then perhaps using `bazel-bin` directly is the best approach.

Let me know if there are any questions.

**Comment by manuelli** [comment]
Thanks Jeremy, this is very helpful.

I think to bypass having to get `drake` to install more targets we can run things directly from `.bazel-bin`.

> On (2) Will the binary be able to load the data resources that it may need?
> 
> In Spartan's config/setup_environment.sh.in, you have:
> 
> export DRAKE_RESOURCE_ROOT=@CMAKE_BINARY_DIR@/install/share/drake
> Assuming Spartan's instructions have developers sourcing that file, then all Drake binaries will look into the install tree for their data resources and should robustly find them (this is supported config, and tested in Drake's CI).
> 
> You will want to be slightly careful because you have two copies of the files on disk now -- the copy in Drake's source tree, and the copy in the install tree. If you have the env var set, it will always be preferred over anything else, so you should reliably get the copy from the install tree. So if you edit a file in Drake's source tree, and then build and run, e.g., $SPARTAN_SOURCE_DIR/drake/bazel-bin/drake/examples/kuka_iiwa_arm/kuka_simulation, it will use the fresh build of the binary, but the older (installed copy) of the data. If this ends up as a pain point, I have ideas we could try to mitigate it, so ping me.

I think that we could just set 
```
export DRAKE_RESOURCE_ROOT=@CMAKE_SOURCE_DIR@/drake
```

and this would ensure that resources are found using `drake` source tree. This keeps consistency between `drake` binaries and resources.

**Comment by jwnimmer-tri** [comment]
> I think that we could just set
> `export DRAKE_RESOURCE_ROOT=@CMAKE_SOURCE_DIR@/drake`
> and this would ensure that resources are found using drake source tree. This keeps consistency between drake binaries and resources.

True, and good point.

**Comment by manuelli** [comment]
@jwnimmer-tri  So it looks liike `drake/bazel-bin` symlinked to another directory.

```
lrwxrwxrwx  1 manuelli manuelli   115 Oct  5 19:49 bazel-bin -> /home/manuelli/.cache/bazel/_bazel_manuelli/ad76158abdb1289449fe615a0566ffbf/execroot/drake/bazel-out/local-opt/bin

```

is this correct. We have switched to using `docker` for `spartan`. The way we do it is to make an image with all the prereqs installed. Then when doing `docker run` we create the container and mount the `spartan` directory on the host machine. See the README [here](https://github.com/RobotLocomotion/spartan/tree/master/setup/docker) for details. Then we run the make inside the docker. Usually builds will persist across container destruction since the `spartan/build` gets written to the host machine. If the `bazel` build is really symlinked into `~/.cache` then it gets destroyed when we delete the container.

Am I interpreting this correctly? If I am interpreting this correctly is there a way to force the bazel build to not symlink the `bazel-bin` folder?

**Comment by jwnimmer-tri** [comment]
If you are compiling inside a Docker, but then running outside that Docker, then you are risking a mismatch between the build-time and run-time environments.  I guess if you ensure that the same versions of, e.g., `libglib2.0-0` are installed in both the build and run environments, then at least the simple things like `libdrake.so` would be relatively robust to the differences.  I worry about things with more complicated runtimes though, like python software.

In any case, if you want to preserve the build artifacts across the Docker and non-Docker filesystem namespaces, then I think `--output_base` is what you want, e.g.,:
```bash
bazel --output_base=drake-build //...
```

Note that because `output_base` changes Bazel server start-up, it must appear _before_ the command `build`, not after like the `BAZEL_ARGS`.  I would probably do something like this:
```
set(BAZEL_STARTUP_ARGS "--output_base=${source_dir}/drake-build")
...
ExternalProject_Add(drake
  SOURCE_DIR ${source_dir}/drake
...
  BUILD_COMMAND ${BAZEL_ENV} "${BAZEL}" ${BAZEL_STARTUP_ARGS} build ${BAZEL_ARGS} //... //:install
  INSTALL_COMMAND ${BAZEL_ENV} "${BAZEL}" ${BAZEL_STARTUP_ARGS} run ${BAZEL_ARGS} //:install -- "${CMAKE_INSTALL_PREFIX}"
)
```

Note that `output_base` cannot be set to live _within_ Drake's source tree.  (That mixing confuses Bazel.)  In the above, I've set it to be a sibling to the source.  Possibly something like `${CMAKE_BINARY_DIR}/drake-build` would also work.

Note that, like `BAZEL_ENV` and `BAZEL_ARGS`, the `BAZEL_STARTUP_ARGS` should also be kept identical in every Bazel invocation.  So letting CMake do the work of calling Bazel still seems like a good idea.

**Comment by manuelli** [comment]
Ok thanks we'll try that.

Just for clarification we are are compiling and running inside the docker. The reason for all of this is that because we are using this for development, we don't build `spartan` during the build of the docker image. Rather we mount the `spartan` directory into the docker image and run the build inside it. There is only ever one run environment. The only thing we want is for the build artifacts to persist so if we rm a container and create a new one (based on the same image) then we don't have to recompile.

**Comment by jwnimmer-tri** [comment]
That makes more sense, thanks for the clarification!

**Comment by gizatt** [comment]
I tried following the above, and getting Bazel to spit its artifacts into `spartan/build/drake-build`, but I get an interesting build fail:

```
gizatt@84a11835a153:~/spartan/build$ make -j4
Scanning dependencies of target drake
[  1%] Creating directories for 'drake'
[  3%] No download step for 'drake'
[  5%] No update step for 'drake'
[  7%] No patch step for 'drake'
[  8%] No configure step for 'drake'
[ 10%] Performing build step for 'drake'
............
ERROR: /home/gizatt/spartan/drake/drake/solvers/BUILD:477:1: no such package '@snopt//': Traceback (most recent call last):
	File "/home/gizatt/spartan/build/drake-build/external/bazel_tools/tools/build_defs/repo/git.bzl", line 67
		_clone_or_update(ctx)
	File "/home/gizatt/spartan/build/drake-build/external/bazel_tools/tools/build_defs/repo/git.bzl", line 42, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning snopt:
+ cd /home/gizatt/spartan/build/drake-build/external
+ cd /home/gizatt/spartan/build/drake-build/external/snopt
+ git reset --hard 2ec980370eeb72897135b11570033a19bda885a7
fatal: Could not parse object '2ec980370eeb72897135b11570033a19bda885a7'.
+ git fetch
+ git reset --hard 2ec980370eeb72897135b11570033a19bda885a7
fatal: Could not parse object '2ec980370eeb72897135b11570033a19bda885a7'.
 and referenced by '//drake/solvers:snopt_solver'
ERROR: Analysis of target '//drake/examples/kuka_iiwa_arm/pick_and_place:world_state_test' failed; build aborted
INFO: Elapsed time: 9.293s
FAILED: Build did NOT complete successfully (96 packages loaded)
CMakeFiles/drake.dir/build.make:110: recipe for target 'src/drake-stamp/drake-build' failed
make[2]: *** [src/drake-stamp/drake-build] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/drake.dir/all' failed
make[1]: *** [CMakeFiles/drake.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```
I suspect the cause is that the `snopt` folder within `drake-build` not being a proper git submodule -- it winds up being considered a part of the `spartan` repo.

(@manuelli, workarounds could be to let the bazel build artifacts live elsewhere in the Docker filesystem and possibly the host system... but doing that in a way that allows multiple Spartan builds to coexist on a host system would be tricky. Is that a thing that we want to support? I'd certainly like it, so I can work on different source trees / branches in parallel...)

**Comment by manuelli** [comment]
@gizatt I think most of these changes have been included in other PR's that have already been merged. Can you comment and close if necessary?

**Comment by gizatt** [comment]
Not going to delete the branch, as there are still some relevant fixes in here I eventually want to bring in (largely having to do with visualizing gripper state...), but this shouldn't be merged

**Pull request closed without merging**
