### PR TITLE
Dockerize Spartan

### PR DESCRIPTION
**Pull request by peteflorence**
@manuelli 

Creating this pull request to signal this is coming, but let's not merge until: 

Here is draft of documentation:

```
git clone git@github.com:RobotLocomotion/spartan.git
cd spartan
git submodule init
git submodule update
./setup/docker/docker_build.py
./setup/docker/docker_run.py
cd root/spartan && mkdir build && cd build && cmake .. && make -j8
```

- Note that with this mounting setup, build files will go in `spartan/build` outside of the docker.
- Permissions are not currently set up to be the users'

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/130)

### CODE REVIEW

**Comment by peteflorence** [comment]
confirm builds

**Comment by peteflorence** [comment]
`kuka_iiwa_app` runs from inside docker

image

**Comment by manuelli** [comment]
LGTM pending the minor changes discussed above.

- We should allow for naming of the `docker` container via a command line arg. I would vote for the default name being `spartan`.

**Comment by manuelli** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/130)*

**Comment by manuelli** [comment]
- I changed all scripts to be in python.
- added options for naming the image and the container
- add a README explaining how to use the docker container.

@peteflorence for review

**Comment by manuelli** [comment]
Done. By default I named the image and the container `spartan.`

**Comment by manuelli** [comment]
@patmarion what do you recommend to resolve #132? Do you usually copy your ssh keys into the container?

**Comment by peteflorence** [comment]
Reviewing now.  Remaining list pre merge:

- Solve ssh issues (test: compile and run with Snopt)
- Add documentation for docker build

**Comment by peteflorence** [comment]
All remaining issues addressed

Fixes https://github.com/RobotLocomotion/spartan/issues/132

Merging with @manuelli approval too

**Pull request merged**
