### PR TITLE
Update Drake and ensure compatibility given loss of some prereqs it provided

### PR DESCRIPTION
**Pull request by gizatt**
Needs testing on robot machine (something other than mine, with old build artifacts possibly floating around), but is hopefully good to go to help update Drake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/153)

### CODE REVIEW

**Comment by manuelli** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC2L40TogjpgWNcQgf:-KwC2L40TogjpgWNcQgg:b-97dtpw) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/.gitignore#L6)):*
> ```
> /src/CorlDev/src/ply
> /src/CorlDev/automation/scp_config.yaml
> *snopt.out
> ```

good call, this is getting really annoying

---

*[CMakeLists.txt, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC2OjyeRHRNeMComGK:-KwC2OjyeRHRNeMComGL:bfjwg8m) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/CMakeLists.txt#L109)):*
> ```CMake
>     USES_TERMINAL_BUILD 1
>     CONFIGURE_COMMAND ""
>     BUILD_COMMAND ${BAZEL_ENV} "${BAZEL}" build ${BAZEL_ARGS} //drake/examples/kuka_iiwa_arm/... //:install
> ```

aren't we planning to just build all of drake?

---

*[setup/docker/spartan.dockerfile, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC26hJudjEvXUvIaIW:-KwC26hKy-BdCdK72zGs:b-z1o67b) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/setup/docker/spartan.dockerfile#L32)):*
> ```Dockerfile
> RUN yes "Y" | /tmp/drake_install_prereqs.sh
> 
> COPY ./director/distro/travis/install_deps.sh /tmp/director_install_prereqs.sh
> ```

can we change this to `travis_install_prereqs.sh`

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC2G-nwFf8hISbLu6-:-KwC2G-olAQVxA3WZLsv:bbk555) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/setup/ubuntu/16.04/install_prereqs.sh#L26)):*
> ```Shell
>   libxt-dev \
>   libtheora-dev \
>   libxml2-dev \
> ```

what are all these new dependencies needed for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/153)*

**Comment by gizatt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC2L40TogjpgWNcQgf:-KwC4KcbVL2X2AF5iBAK:b-8fx2u7) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/.gitignore#L6)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

good call, this is getting really annoying
</blockquote></details>

:+1: 

---

*[CMakeLists.txt, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC2OjyeRHRNeMComGK:-KwC2m976dtsUyHqYl8V:byop7y6) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/CMakeLists.txt#L109)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

aren't we planning to just build all of drake?
</blockquote></details>

Yeah but it takes longer -- I just wanted to add this part as it allows simulation of the robot for easier vertical integration testing.

---

*[setup/docker/spartan.dockerfile, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC26hJudjEvXUvIaIW:-KwC3rWOap9SO31Lu5x5:bqq9g6d) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/setup/docker/spartan.dockerfile#L32)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

can we change this to `travis_install_prereqs.sh`
</blockquote></details>

Switched to "director_travis_install_prereqs.sh" -- it's still specific to Director

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC2G-nwFf8hISbLu6-:-KwC2vw3_7r29eb3NM7V:b-x1wkzr) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/setup/ubuntu/16.04/install_prereqs.sh#L26)):*
<details><summary><i>Previously, manuelli (Lucas Manuelli) wrote…</i></summary><blockquote>

what are all these new dependencies needed for?
</blockquote></details>

TBH I'm not sure on most of them. They're dependencies that I think were brought in as dependencies by the handful of modules no longer available from Drake (mostly VTK5 things). I got library-not-found errors in Director's FLANN and PCL builds until I had these installed.

Also, note that I reordered the library list here to make it alphabetical (it was getting haphazard), so some of them might have been there already, but in another place in the list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/153)*

**Comment by manuelli** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-KwC2OjyeRHRNeMComGK:-KwCBb3qzRjtvZO-9ynn:b-nr9v58) ([raw file](https://github.com/robotlocomotion/spartan/blob/05efcf3832203597256b36581fd834278fde8f14/CMakeLists.txt#L109)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Yeah but it takes longer -- I just wanted to add this part as it allows simulation of the robot for easier vertical integration testing.
</blockquote></details>

ok, lets save that change for a future PR that also fixes the `bazel-bin` symlink issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/153)*

**Comment by manuelli** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/153#-:-KwCCBoXE-YtB3Pq_tqm:bnfp4nl)*

**Pull request merged**
