### PR TITLE
pulled drake master and edited startup script

### PR DESCRIPTION
**Pull request by kmuhlrad**
An updated version of drake (commit 5b5d80b), and a change to a script called by docker_build.py to correctly build drake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/254)

### CODE REVIEW

**Comment by gizatt** [comment]
jenkins please test

On Feb 16, 2018 18:12, "rlg-jenkins" <notifications@github.com> wrote:

Can one of the admins verify this patch?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RobotLocomotion/spartan/pull/254#issuecomment-366385579>,
or mute the thread

**Comment by gizatt** [comment]
Sorry for delay, I just whitelisted you so any additional PRs you make (or commits you make to this one) will be tested automatically

**Comment by manuelli** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/docker/spartan.dockerfile, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/254#-L5nhJu5XcP5o8wbKLai:-L5nhJu5XcP5o8wbKLaj:bkygui1) ([raw file](https://github.com/robotlocomotion/spartan/blob/65ca8a0bb6684578ff170710b642675309fb2bc1/setup/docker/spartan.dockerfile#L30)):*
> ```Dockerfile
> RUN yes "Y" | /tmp/spartan_install_prereqs.sh
> 
> COPY ./drake/setup/ubuntu/16.04/binary_distribution/install_prereqs.sh /tmp/binary_distribution/install_prereqs.sh
> ```

So this is now required in addition to the `16.04/install_prereqs.sh`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/254)*

**Comment by manuelli** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/254)*

**Comment by jwnimmer-tri** [comment]
FYI If you can recursively copy `drake/setup/ubuntu/16.04/**`, instead of listing its contents one-by-one, that's would be more robust to changes in Drake.  See for example RobotLocomotion/drake#8106 where even more files will soon become required.

**Pull request merged**
