### PR TITLE
Adds some perception utilities

### PR DESCRIPTION
**Pull request by gizatt**
This adds some utilities I've been using in my perception work:

- PCL, OpenCV, and VTK cpp utilities
- OpenCV python utilities (mostly for visualization)
- A ROS point cloud grabber for convenient visualization and grabbing of ROS-published RGBD frames. It saves synchronized, rectified RGB and D frames by extracting everything from the structured point cloud. It does normal estimation with PCL's grid normal estimation algorithm, too. Good for saving point clouds and frames for prototyping your pose estimation algorithms.
- Adds usbutils to the docker apt-get script to ensure `lsusb` is available, for debugging sensors that don't show up when you plug them in.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/spartan/195)

### CODE REVIEW

**Comment by gizatt** [comment]
Oops, don't worry about reviewing for a few more minutes, this wasn't meant to be submitted yet

**Comment by gizatt** [comment]
OK, good to go

**Comment by manuelli** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/catkin_projects/perception_sandbox/CMakeLists.txt, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/195#-Kz5PW-OuyBnNqmtB9ag:-Kz5PW-OuyBnNqmtB9ah:b-c0hfu6) ([raw file](https://github.com/robotlocomotion/spartan/blob/ddedd09f7bdfeecfeafe149f91ea313756a55420/src/catkin_projects/perception_sandbox/CMakeLists.txt#L6)):*
> ```CMake
> 
> find_package(drake CONFIG REQUIRED)
> find_package(Eigen3 3.3.3 REQUIRED)
> ```

Is this finding the Eigen provided by drake or a different one?

---

*[src/catkin_projects/perception_sandbox/CMakeLists.txt, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/195#-Kz5PY_mjSPICRp7CJeX:-Kz5PY_mjSPICRp7CJeY:b4ufgjg) ([raw file](https://github.com/robotlocomotion/spartan/blob/ddedd09f7bdfeecfeafe149f91ea313756a55420/src/catkin_projects/perception_sandbox/CMakeLists.txt#L7)):*
> ```CMake
> find_package(drake CONFIG REQUIRED)
> find_package(Eigen3 3.3.3 REQUIRED)
> find_package(PCL CONFIG REQUIRED)
> ```

Which PCL is this? Is it system installed or provided by director?

---

*[src/catkin_projects/perception_sandbox/CMakeLists.txt, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/195#-Kz5PcDA9wuwNunizsa2:-Kz5PcDA9wuwNunizsa3:b8yqte0) ([raw file](https://github.com/robotlocomotion/spartan/blob/ddedd09f7bdfeecfeafe149f91ea313756a55420/src/catkin_projects/perception_sandbox/CMakeLists.txt#L9)):*
> ```CMake
> find_package(PCL CONFIG REQUIRED)
> 
> find_package(OpenCV REQUIRED)
> ```

Which OpenCV is this? Is it system installed or provided by director?

---

*[src/catkin_projects/perception_sandbox/CMakeLists.txt, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/195#-Kz5PjTHfHF6NKQM7ECm:-Kz5PjTHfHF6NKQM7ECn:b9lvaqn) ([raw file](https://github.com/robotlocomotion/spartan/blob/ddedd09f7bdfeecfeafe149f91ea313756a55420/src/catkin_projects/perception_sandbox/CMakeLists.txt#L44)):*
> ```CMake
> # There must be a better way... gotta figure out
> # how to make find_package work for common utils
> include_directories(${CMAKE_INSTALL_PREFIX}/include)
> ```

fine for now but make an issue to track this.

---

*[src/catkin_projects/perception_sandbox/package.xml, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/195#-Kz5PoELftwCpr4X_o5o:-Kz5PoELftwCpr4X_o5p:bxwnu6m) ([raw file](https://github.com/robotlocomotion/spartan/blob/ddedd09f7bdfeecfeafe149f91ea313756a55420/src/catkin_projects/perception_sandbox/package.xml#L48)):*
> ```XML
>   <build_depend>image_transport</build_depend>
>   <build_depend>libpcl-all-dev</build_depend>
>   <build_depend>pcl_ros</build_depend>
> ```

So if you are using pcl_ros does this conflict with the PCL version built by director?

---

*[src/common_utils/CMakeLists.txt, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/spartan/195#-Kz5Q2ZYYYO3n8sVAC0r:-Kz5Q2ZYYYO3n8sVAC0s:b-63aerk) ([raw file](https://github.com/robotlocomotion/spartan/blob/ddedd09f7bdfeecfeafe149f91ea313756a55420/src/common_utils/CMakeLists.txt#L11)):*
> ```CMake
> include_directories(${OpenCV_INCLUDE_DIRS})
> 
> find_package(PCL REQUIRED)
> ```

Same question as before, is this system PCL or PCL built by director?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/195)*

**Comment by manuelli** [comment]
:lgtm:

---

Reviewed 1 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/spartan/195#-:-Kz5fMsJTBYXP_9W0GR4:bnfp4nl)*

**Pull request merged**
